language: c++
compiler:
  - g++
dist: trusty
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && NODE_VERSION=10"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - curl
      - g++-7
      - cmake
      - libxml2-dev
      - libxslt1-dev
before_install:
  - eval "${MATRIX_EVAL}"
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  - source ~/.bashrc
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

install:
  - npm i