language: c++
compiler:
  - gcc
dist: trusty
env:
  matrix:
    - NODE_VERSION="10"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - curl
      - g++-7
      - cmake
      - libxml2-dev
      - libxslt1-dev
before_install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  - source ~/.bashrc
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

install:
  - npm i