#pragma once

#include <string>

namespace Utils
{

// Build a string from the last xmlError generated by libxml.
std::string GetLastXmlError();

// Remove the leading and trailing whitespaces of a string.
void TrimString(std::string &string);

}
