name: Build and test
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install libxml2-dev libxslt1-dev
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.20.x'
        run: npm install -g node-gyp
      - name: Build and test
        run: |
          npm install
          npm test
